### ISSUE TITLE
Version 1.3.5 doesn't work

### ISSUE THREAD

**Issue by iteux** [nicolodiamante/SiriGPT#13] opened 2023-07-01 05:40 UTC
Error: The action is going to send the object to the Calendar. This is not allowed. This can be enabled in the System Settings.

<img width="302" alt="Снимок экрана 2023-07-01 в 08 32 10" src="https://github.com/nicolodiamante/SiriGPT/assets/51264528/86a02253-6d99-4bbe-86ca-f914bdb11a33">

But there was no request to access the calendar and this cannot be enabled in the settings.

And also, fix the fact that the command doesn't work when data sharing is disabled (I don't need it).

MacOS Monterey 12.6.6, iOS 16.5

**Comment by nicolodiamante** [comment] 2023-07-01 11:13
Hello @Harosatchi 

I'm sorry you're having trouble getting the shortcut to work. Is my understanding correct that you were asked to access the calendar even though you had selected Data Sharing Off?

**Comment by iteux** [comment] 2023-07-01 11:23
At first, I disabled data sharing during the initial setup, but because of this, the shortcut refused to work on the phone. Then I turned on data sharing (1), but this error occurred.

**Comment by iteux** [comment] 2023-07-11 08:06
I reinstalled and gave the permissions. But even now it doesn't want to run, either on a mac or on an iPhone.

Same Error: The action is going to send 107 objects to the Calendar. This is not allowed. This can be enabled in the Settings.
![IMG_3486](https://github.com/nicolodiamante/SiriGPT/assets/51264528/f5a3f7d4-4045-45fb-83d0-df7033ef33ba)

_**But there is no such thing anywhere in the settings.**_

**Comment by nicolodiamante** [comment] 2023-07-11 08:27
Hello, @Harosatchi 

I wanted to let you know that I'm currently working on resolving the issue you've encountered. I apologise for any inconvenience this may have caused you.

If you could kindly let me know whether you have been turning off data sharing when setting up the shortcut, it would greatly help me understand the root cause of the problem. I believe that disabling data sharing the first time you set the shortcut might be the reason behind the issue you're facing initially. Please be patient with me as I am actively working on releasing a new update very soon.

Thank you for your patience!

**Comment by iteux** [comment] 2023-07-11 08:31
> whether you have been turning off data sharing when setting up the shortcut

There was a new installation with sharing enabled (1).

**Comment by nicolodiamante** [comment] 2023-07-11 09:40
That was just a small upgrade, but don't worry, I'll be uploading version 13.6 soon!

**Comment by iteux** [comment] 2023-07-14 14:08
Thanks for the 1.3.6 update, everything is working now.

I would like to mention a couple of points.

1) In the section about the clipboard, it written "tex" instead of "text".
<img width="660" alt="Снимок экрана 2023-07-14 в 13 39 29" src="https://github.com/nicolodiamante/SiriGPT/assets/51264528/4a62c94d-f038-4a89-96ac-74ab80212044">


2) Inaccuracies of machine translation into Russian:
- the translation of the word "image" will be more correct as "изображение", not "образ" (different words with the same translation)
- "до свидания" is better to write with a capital letter "До свидания" [Goodbye]
- instead of "Проверить мое расписание" (indefinite verb form), it is better to write "проверь мое расписание" (imperative mood of the verb) [check my schedule]

**Comment by nicolodiamante** [comment] 2023-07-14 14:27
Hi @Harosatchi ,

Great news that everything works now! By the way, I have to thank you for helping me with that Russian translation and for spotting typos in the text - it helped me tremendously. Honestly, I can't thank you enough for your keen eye! Rest assured, I'll take care of the changes you suggested.

**Closed as completed** 2023-07-15 09:14 UTC
